#Requires -Version 5.1

<#
.SYNOPSIS
Imports the PipeDFe PowerShell module in development mode.

.DESCRIPTION
Performs a clean development import of the PipeDFe module directly
from the local source tree.

The script:
  1. Validates the module manifest.
  2. Removes any previously loaded instance of the module.
  3. Imports the module from its local manifest.
  4. Displays module metadata and exported commands.
  5. Optionally runs PSScriptAnalyzer against the source tree.

The script is designed for both interactive development and automation.

Exit codes:
  0 - Operation completed successfully.
  1 - Module import or validation failed.
  2 - Linting failed when -FailOnLint was specified.

.PARAMETER Quiet
Suppresses verbose output generated by Import-Module.

.PARAMETER SkipLint
Skips the PSScriptAnalyzer validation step.

.PARAMETER FailOnLint
Causes the script to exit with code 2 when PSScriptAnalyzer
reports one or more errors or warnings.

.PARAMETER PassThru
Returns a summary object containing module and lint information.
Useful when invoking this script from another PowerShell script.

.PARAMETER WhatIf
Shows what would happen without modifying the current session.

.EXAMPLE
PS C:\PipeDFe> .\tools\Invoke-DevImport.ps1

Imports the module and runs PSScriptAnalyzer.

.EXAMPLE
PS C:\PipeDFe> .\tools\Invoke-DevImport.ps1 -Quiet

Imports the module without displaying Import-Module verbose output.

.EXAMPLE
PS C:\PipeDFe> .\tools\Invoke-DevImport.ps1 -SkipLint

Imports the module without running PSScriptAnalyzer.

.EXAMPLE
PS C:\PipeDFe> .\tools\Invoke-DevImport.ps1 -FailOnLint

Imports the module and returns exit code 2 if linting reports
warnings or errors.

.EXAMPLE
PS C:\PipeDFe> $result = .\tools\Invoke-DevImport.ps1 -PassThru

Imports the module and captures the resulting summary object.

.NOTES
  File:     Invoke-DevImport.ps1
  Project:  PipeDFe
  Requires: PowerShell 5.1+
#>

[Diagnostics.CodeAnalysis.SuppressMessageAttribute(
    'PSAvoidUsingWriteHost',
    '',
    Justification = 'This script is an interactive development CLI.'
)]
[CmdletBinding(SupportsShouldProcess)]
param (
    [Parameter()]
    [switch]$Quiet,

    [Parameter()]
    [switch]$SkipLint,

    [Parameter()]
    [switch]$FailOnLint,

    [Parameter()]
    [switch]$PassThru
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

#region Constants
$Script:ModuleName   = 'PipeDFe'
$Script:ModuleRoot   = Split-Path -Path $PSScriptRoot      -Parent
$Script:ManifestPath = Join-Path  -Path $Script:ModuleRoot -ChildPath "$Script:ModuleName.psd1"
$Script:SourcePath   = Join-Path  -Path $Script:ModuleRoot -ChildPath 'src'

$Script:AnalyzerSettingsPath = Join-Path -Path $Script:ModuleRoot -ChildPath 'PSScriptAnalyzerSettings.psd1'
#endregion

#region Helper Functions
function Write-Banner {
    [CmdletBinding()]
    [OutputType([void])]
    param ()

    Write-Host ''
    Write-Host '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━' -ForegroundColor DarkGray
    Write-Host '  PipeDFe - Dev Import' -ForegroundColor Cyan
    Write-Host '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━' -ForegroundColor DarkGray
    Write-Host ''
}

function Write-Section {
    [CmdletBinding()]
    [OutputType([void])]
    param (
        [Parameter(Mandatory)]
        [string]$Title
    )

    Write-Host ''
    Write-Host "  $Title" -ForegroundColor Cyan
    Write-Host ''
}

function Write-Success {
    [CmdletBinding()]
    [OutputType([void])]
    param (
        [Parameter(Mandatory)]
        [string]$Message
    )

    Write-Host "  [OK] $Message" -ForegroundColor Green
}

function Write-WarningMessage {
    [CmdletBinding()]
    [OutputType([void])]
    param (
        [Parameter(Mandatory)]
        [string]$Message
    )

    Write-Host "  [WARN] $Message" -ForegroundColor Yellow
}

function Write-ErrorMessage {
    [CmdletBinding()]
    [OutputType([void])]
    param (
        [Parameter(Mandatory)]
        [string]$Message
    )

    Write-Host "  [ERROR] $Message" -ForegroundColor Red
}

function Test-DevEnvironment {
    [CmdletBinding()]
    [OutputType([bool])]
    param ()

    $errors = [System.Collections.Generic.List[string]]::new()

    if (-not (Test-Path -LiteralPath $Script:ModuleRoot -PathType Container)) {
        $errors.Add("Module root was not found: $Script:ModuleRoot") | Out-Null
    }

    if (-not (Test-Path -LiteralPath $Script:ManifestPath -PathType Leaf)) {
        $errors.Add("Module manifest was not found: $Script:ManifestPath") | Out-Null
    }

    if (-not (Test-Path -LiteralPath $Script:SourcePath -PathType Container)) {
        $errors.Add("Source directory was not found: $Script:SourcePath") | Out-Null
    }

    if ($errors.Count -gt 0) {
        foreach ($errorMessage in $errors) {
            Write-ErrorMessage -Message $errorMessage
        }

        return $false
    }

    return $true
}

function Get-ManifestInfo {
    [CmdletBinding()]
    [OutputType([System.Management.Automation.PSModuleInfo])]
    param ()

    try {
        Test-ModuleManifest -Path $Script:ManifestPath -ErrorAction Stop
    } catch {
        Write-ErrorMessage -Message "Invalid module manifest. $($_.Exception.Message)"
        $null
    }
}

function Remove-LoadedModule {
    [CmdletBinding(SupportsShouldProcess)]
    [OutputType([void])]
    param ()

    $loadedModules = @(Get-Module -Name $Script:ModuleName -ErrorAction SilentlyContinue)

    if ($loadedModules.Count -eq 0) {
        return
    }

    foreach ($loadedModule in $loadedModules) {
        Write-Host "  Removing loaded module: v$($loadedModule.Version)" -ForegroundColor Yellow

        if ($PSCmdlet.ShouldProcess($loadedModule.Name, 'Remove loaded module')) {
            try {
                Remove-Module -Name $loadedModule.Name -Force -ErrorAction Stop
            } catch {
                throw "Failed to remove loaded module '$($loadedModule.Name)'. $($_.Exception.Message)"
            }
        }
    }
}

function Import-DevModule {
    [CmdletBinding()]
    [OutputType([System.Management.Automation.PSModuleInfo])]
    param ()

    Write-Host "  Importing from: $Script:ManifestPath" -ForegroundColor Gray
    Write-Host ''

    try {
        $importParams = @{
            Name        = $Script:ManifestPath
            Force       = $true
            ErrorAction = 'Stop'
        }

        if (-not $Quiet) {
            $importParams['Verbose'] = $true
        }

        Import-Module @importParams
    } catch {
        throw "Module import failed. $($_.Exception.Message)"
    }

    $module = Get-Module -Name $Script:ModuleName -ErrorAction SilentlyContinue

    if (-not $module) {
        throw "Module '$Script:ModuleName' was not loaded after import."
    }

    $module
}

function Show-ModuleSummary {
    [CmdletBinding()]
    [OutputType([void])]
    param (
        [Parameter(Mandatory)]
        [System.Management.Automation.PSModuleInfo]$Module
    )

    Write-Section -Title 'Module Summary'

    Write-Host "  Module   : $($Module.Name) v$($Module.Version)" -ForegroundColor Green
    Write-Host "  Path     : $($Module.Path)" -ForegroundColor Gray
    Write-Host "  Commands : $($Module.ExportedCommands.Count) exported" -ForegroundColor Green

    if ($Module.ExportedCommands.Count -gt 0) {
        Write-Host ''
        Write-Host '  Exported commands:' -ForegroundColor Gray

        foreach ($commandName in ($Module.ExportedCommands.Keys | Sort-Object)) {
            Write-Host "    $commandName" -ForegroundColor DarkCyan
        }
    }

    Write-Host ''
}

function Invoke-DevLint {
    [CmdletBinding()]
    [OutputType([pscustomobject])]
    param ()

    $result = [PSCustomObject]@{
        Available = $false
        Executed  = $false
        Issues    = @()
        Count     = 0
        Failed    = $false
    }

    if ($SkipLint) {
        Write-Host '  PSScriptAnalyzer : skipped by -SkipLint' -ForegroundColor DarkGray

        return $result
    }

    $analyzer = Get-Module -Name PSScriptAnalyzer -ListAvailable -ErrorAction SilentlyContinue

    if (-not $analyzer) {
        Write-WarningMessage -Message 'PSScriptAnalyzer is not installed. Lint skipped.'
        Write-Host '  Install with: Install-Module PSScriptAnalyzer -Scope CurrentUser' -ForegroundColor DarkGray

        return $result
    }

    $result.Available = $true

    Write-Section -Title 'PSScriptAnalyzer'

    Write-Host "  Analyzer : v$($analyzer[0].Version)" -ForegroundColor Gray
    Write-Host "  Path     : $Script:SourcePath" -ForegroundColor Gray

    if (Test-Path -LiteralPath $Script:AnalyzerSettingsPath -PathType Leaf) {
        Write-Host "  Settings : $Script:AnalyzerSettingsPath" -ForegroundColor Gray
    }

    Write-Host ''
    Write-Host '  Running PSScriptAnalyzer...' -ForegroundColor Gray
    Write-Host ''

    $analyzerParams = @{
        Path        = $Script:SourcePath
        Recurse     = $true
        Severity    = @('Error', 'Warning')
        ErrorAction = 'Stop'
    }

    if (Test-Path -LiteralPath $Script:AnalyzerSettingsPath -PathType Leaf) {
        $analyzerParams['Settings'] = $Script:AnalyzerSettingsPath
    }

    try {
        $lintResults = @(Invoke-ScriptAnalyzer @analyzerParams)
    } catch {
        throw "PSScriptAnalyzer execution failed. $($_.Exception.Message)"
    }

    $result.Executed = $true
    $result.Issues   = $lintResults
    $result.Count    = $lintResults.Count
    $result.Failed   = $lintResults.Count -gt 0

    if ($lintResults.Count -eq 0) {
        Write-Success -Message 'PSScriptAnalyzer found no issues.'

        return $result
    }

    Write-WarningMessage -Message "PSScriptAnalyzer found $($lintResults.Count) issue(s)."

    Write-Host ''

    $lintResults |
        Sort-Object Severity, ScriptName, Line |
        Format-Table -AutoSize -Property Severity, RuleName, ScriptName, Line, Message |
        Out-Host

    Write-Host ''

    $result
}

function New-DevImportResult {
    [Diagnostics.CodeAnalysis.SuppressMessageAttribute(
        'PSUseShouldProcessForStateChangingFunctions',
        '',
        Justification = 'Result builder — no state is changed.'
    )]
    [CmdletBinding()]
    [OutputType([pscustomobject])]
    param (
        [Parameter(Mandatory)]
        [System.Management.Automation.PSModuleInfo]$Module,

        [Parameter(Mandatory)]
        [pscustomobject]$LintResult
    )

    [PSCustomObject]@{
        Success          = $true
        ModuleName       = $Module.Name
        ModuleVersion    = $Module.Version
        ModulePath       = $Module.Path
        ExportedCommands = @($Module.ExportedCommands.Keys | Sort-Object)
        CommandCount     = $Module.ExportedCommands.Count
        LintAvailable    = $LintResult.Available
        LintExecuted     = $LintResult.Executed
        LintIssueCount   = $LintResult.Count
        LintFailed       = $LintResult.Failed
    }
}
#endregion

#region Main
Write-Banner

Write-Section -Title 'Validation'

if (-not (Test-DevEnvironment)) {
    if ($PassThru) {
        return [PSCustomObject]@{
            Success = $false
            Error   = 'Development environment validation failed.'
        }
    }

    exit 1
}

$manifestInfo = Get-ManifestInfo

if (-not $manifestInfo) {
    if ($PassThru) {
        return [PSCustomObject]@{
            Success = $false
            Error   = 'Module manifest validation failed.'
        }
    }

    exit 1
}

Write-Success -Message "Manifest validated: v$($manifestInfo.Version)"

if ($WhatIfPreference) {
    Write-Host ''
    Write-Host '  WhatIf: No changes were made.' -ForegroundColor Yellow
    Write-Host ''

    return
}

try {
    Write-Section -Title 'Module Import'

    Remove-LoadedModule

    $module = Import-DevModule

    Write-Success -Message 'Module imported successfully.'

    Show-ModuleSummary -Module $module

    $lintResult = Invoke-DevLint

    $result = New-DevImportResult -Module $module -LintResult $lintResult

    Write-Host ''
    Write-Host '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━' -ForegroundColor DarkGray

    if ($lintResult.Failed -and $FailOnLint) {
        Write-Host '  RESULT   : FAILED (lint issues)' -ForegroundColor Red
        Write-Host "  Issues   : $($lintResult.Count)" -ForegroundColor Yellow
        Write-Host '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━' -ForegroundColor DarkGray
        Write-Host ''

        if ($PassThru) {
            return $result
        }

        exit 2
    }

    Write-Host '  RESULT   : SUCCESS' -ForegroundColor Green
    Write-Host '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━' -ForegroundColor DarkGray
    Write-Host ''

    if ($PassThru) {
        return $result
    }

    exit 0
} catch {
    Write-Host ''
    Write-ErrorMessage -Message $_.Exception.Message
    Write-Host ''

    if ($PassThru) {
        return [PSCustomObject]@{
            Success = $false
            Error   = $_.Exception.Message
        }
    }

    exit 1
}
#endregion
